<a href="https://colab.research.google.com/github/hawk-in-cloud/PythonLearning/blob/main/Numpy/NumpyLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 关于numpy的学习

In [ ]:
# 关于np：提供一个特殊的矩阵数组

# 通过实例来讲解np：

## np的所有计算均围绕np.array()来进行

import numpy as np

a = np.array([1,2,3,4,5])

b = np.zeros((3,2)) # 创造全零矩阵数组

a,b

(array([1, 2, 3, 4, 5]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [ ]:
## 获取数组尺寸

a.shape,b.shape

((5,), (3, 2))

In [ ]:
## 递增数组
c = np.arange(3,7)
d = np.arange(8,1)
c,d

(array([3, 4, 5, 6]), array([], dtype=int64))

In [ ]:
e = np.random.rand(3,4,2)
e

array([[[0.92805372, 0.09120496],
        [0.27619739, 0.61856266],
        [0.23451614, 0.12005294],
        [0.2829665 , 0.48208777]],

       [[0.06647437, 0.28855748],
        [0.69393063, 0.23861124],
        [0.07003847, 0.12577642],
        [0.22224596, 0.2526562 ]],

       [[0.96381539, 0.85027152],
        [0.63948566, 0.98274311],
        [0.19069686, 0.57339129],
        [0.36358408, 0.9344702 ]]])

In [ ]:
# 基本运算
a = np.array([[1,2],[3,4]], dtype=np.int64)

b = np.array([[3,4],[2,1]], dtype=np.int64)

#基本加减乘除
print("a+b=\n",a+b)
print("a-b=\n",a-b)
print("a/b=\n",a/b)
print("a*b=\n",a*b)

#点乘/矩阵乘法
print("ab点乘=\n",np.dot(a,b))
print("ab矩阵乘法=\n",a @ b)

a+b=
 [[4 6]
 [5 5]]
a-b=
 [[-2 -2]
 [ 1  3]]
a/b=
 [[0.33333333 0.5       ]
 [1.5        4.        ]]
a*b=
 [[3 8]
 [6 4]]
ab点乘=
 [[ 7  6]
 [17 16]]
ab矩阵乘法=
 [[ 7  6]
 [17 16]]


In [ ]:
# 关于标准差、均值、方差

f = np.random.rand(3,4,3) #生成1个3*4*3的数组
mean = np.mean(f) #求f数组的所有单位的均值
mean1 = np.mean(f, axis=-1)#求f数组的最后一维的均值
mean2 = np.mean(f, axis=-1, keepdims=True)#求f数组的最后一维的均值,不会因为求均值而降维
#print("f = " , f)
#print("mean = " , mean)
#print("mean1 = " , mean1)
#print("mean2 = " , mean2)

#方差/标准差也是类似
var = np.var(f, axis=-1, keepdims=True)
std = np.std(f, axis=-1, keepdims=True)
var,std

(array([[[0.05595181],
         [0.06146282],
         [0.00751902],
         [0.04905921]],
 
        [[0.03092912],
         [0.03608239],
         [0.05351458],
         [0.01285094]],
 
        [[0.05225308],
         [0.00806962],
         [0.12760574],
         [0.0212285 ]]]),
 array([[[0.23654134],
         [0.24791697],
         [0.08671228],
         [0.22149315]],
 
        [[0.17586678],
         [0.18995366],
         [0.23133218],
         [0.113362  ]],
 
        [[0.22858933],
         [0.08983104],
         [0.35721946],
         [0.14570002]]]))